import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import DefaultHeader from "./components/default-header/DefaultHeader";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // normal, medium, bold
});

export const metadata: Metadata = {
  title: "Ivan Marquez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} antialiased`}>
        <DefaultHeader />
        {children}
      </body>
    </html>
  );
}
