import { render, screen } from "@testing-library/react";
import React from "react";

// Mock de Next.js font
jest.mock("next/font/google", () => ({
  Roboto: jest.fn(() => ({ className: "mock-roboto" })),
}));

// Mock de DefaultHeader
jest.mock("./components/default-header/DefaultHeader", () => ({
  __esModule: true,
  default: () => <header data-testid="default-header">Header</header>,
}));

// Importamos lo que vamos a testear
import { LayoutContent, metadata } from "./layout";

describe("LayoutContent", () => {
  test("renders DefaultHeader and children", () => {
    render(
      <LayoutContent>
        <div data-testid="child">Child content</div>
      </LayoutContent>
    );

    // Header
    expect(screen.getByTestId("default-header")).toBeInTheDocument();

    // Children
    expect(screen.getByTestId("child")).toBeInTheDocument();
  });

  // * ESTO CUBRIRIA LA LINEA DEL ROOT LAYOUT PERO DA UN ERROR DE CONSOLA * //
  // console.error
  // In HTML, <html> cannot be a child of <div>.
  // This will cause a hydration error.
  // * DESCOMENTAR SI ES NECESARIO * //

  // describe("RootLayout", () => {
  //   test("renders DefaultHeader and children with correct classes", () => {
  //     render(
  //       <RootLayout>
  //         <div data-testid="child">Child content</div>
  //       </RootLayout>
  //     );

  //     // Verifica que el header se renderiza
  //     expect(screen.getByTestId("default-header")).toBeInTheDocument();

  //     // Verifica que los children se renderizan
  //     expect(screen.getByTestId("child")).toBeInTheDocument();

  //     // Verifica que el body tenga la clase del font mockeada
  //     const body = document.querySelector("body");
  //     expect(body).toHaveClass("mock-roboto");
  //     expect(body).toHaveClass("antialiased");
  //   });
  // });
});

describe("RootLayout metadata", () => {
  test("has correct title and description", () => {
    expect(metadata).toHaveProperty("title", "Ivan Marquez");
    expect(metadata).toHaveProperty(
      "description",
      "Generated by create next app"
    );
  });
});
